### ISSUE TITLE
Nested placeholder don't works with argument

### ISSUE THREAD

**Issue by ascpial** [Andre601/Shortcut-Expansion#3]
When using nested placeholders (e.g. `%changeoutput_equals_input:{objective_score_language}_matcher:1_ifmatch:EN_else:Otherlanguage%`) with replacements (e.g. `/papi parse me %shortcut_trad:test`), the expansion raises an error : `java.lang.NumberFormatException: For input string: "objective_score_language"`.

I see two ways to fix this issue : replace the `{n}` for replacements with other chars e.g. `<n>`, or add a check to only check numbers when checking for replacements.

**Comment by Andre601** [comment]
I can't really see where this is caused by the shortcut expansion?

**Comment by Andre601** [comment]
I can see now what you mean. Haven't looked into this expansion for a while so I was a bit confused.

This sadly isn't as easy to fix as you may think. I use a method provided by Java that replaces `{n}` with whatever values I give, so if I want this to work, would I need to figure out another system to make this work. Perhaps with Regex, but that could have a negative impact on performance if the amount of matches is too high...

Need to look into this.

**Comment by ascpial** [comment]
Thanks you for your work!

**Comment by Andre601** [comment]
Mind testing out this jar (Zipped it as GitHub doesn't support jar uploads. So you have to unzip it)

[Shortcut-1.2.0.zip](https://github.com/Andre601/Shortcut-Expansion/files/10501116/Shortcut-1.2.0.zip)

**Comment by ascpial** [comment]
I tested it, and it seems like the replacement don't works now.

The command do not crash anymore, but returns `{0}` without replacing the value.

**Comment by Andre601** [comment]
That's strange, from my testing did it work fine.

Used this file:
```
Value 1: {0}
Value 2: {1}
Missing Value: {2}
```
And tested with the following commands:
```shell
papi parse --null %shortcut_test:apple:pineapple:banana%
papi parse --null %shortcut_test:apple:pineapple%
```

Results:
```
[17:01:41] [Server thread/INFO]: Value 1: apple
Value 2: pineapple
Missing Value: banana
[17:01:48] [Server thread/INFO]: Value 1: apple
Value 2: pineapple
Missing Value: {2}
```
Just in case, remember that this expansion parses custom replacements before any PAPI placeholders, so if the `{0}` comes from such a placeholder, you have to accept that it won't work like this.

**Comment by ascpial** [comment]
I have this in my shortcut file:

```
%changeoutput_equals_input:{objective_score_language}_matcher:1_ifmatch:{0}_else:Otherlanguage%
```

When I run `/papi parse ascpial %shortcut_trad_en:test%` the result is `{0}`.

If my score is different from 1, the output is correct (`OtherLanguage`)

I tried adding a new line with `{0}` and it and it also returns `{0}`.

**Comment by Andre601** [comment]
I found the issue. Accidentally checked for if the number of arguments was 1 to return text without handling replacements...

Please try this version now:

[Shortcut-1.2.1.zip](https://github.com/Andre601/Shortcut-Expansion/files/10501758/Shortcut-1.2.1.zip)

**Comment by ascpial** [comment]
Works perfectly now! :ok_hand:

**Comment by Andre601** [comment]
Okay. Will later merge the PR and publish it.

**Comment by Andre601** [comment]
Should now be live on the eCloud. It may require verification from the staff there before you can download it through PlaceholderAPI
