### ISSUE TITLE
UTF-16 encoded .txt files aren't parsed

### ISSUE THREAD

**Issue by CyanMatter** [Andre601/Shortcut-Expansion#5]
This is not quite a bug... but it did bug me. 😉
After a few hours looking into an issue where PlaceholderAPI refused to parse *some* `.txt` files in the `shortcuts` folder, I found that these files had in common that I had written them in UTF-16 encoding. Switching to UTF-8 instead resolved my issue.
I figured I might as well mention this here, hoping it helps someone else.
Thank you for maintaining shortcut! It's been a game changer for placeholders.

**Comment by Andre601** [comment]
Yeah. Not really something I could probably fix here... And also no real reason to have this issue opened to begin with.
