### ISSUE TITLE
Cant download expansion by using command.

### ISSUE THREAD

**Issue by Mideks** [Andre601/Shortcut-Expansion#6]
When i type 
`papi ecloud download Shortcut`
I get error: The expansion 'Shortcut' is not verified and can only be downloaded manually from https : / / placeholderapi.com/ecloud

**Comment by Andre601** [comment]
Not an issue. It's just that the expansion isn't verified on the ecloud, just like the error tells you.

Go to the ecloud and download it manually.

**Comment by Mideks** [comment]
I was just thinking that maybe this is not the way it should be. After all, the plugin page gives a command that should sort of allow downloading, but it doesn't...
