### ISSUE TITLE
Subfolders - Addition

### ISSUE THREAD

**Issue by kristophergeo** [Andre601/Shortcut-Expansion#8]
Hey @Andre601! could you possibly add support for subfolders to the shortcut expansion, i do have quite a few shortcuts and it would be better to organize em a lil w folders

**Comment by Andre601** [comment]
Have you tried to add the folder name to the file? Like `folder/file`? Not sure if that actually works. May work on it in the future if it doesn't.

**Comment by kristophergeo** [comment]
like `test/%parseother_{superior_island_leader}_{score_variables_island-wart-deposited_int}%` if that shortcut is in a folder named test?

**Comment by Andre601** [comment]
Uh, no?

I meant `%shortcut_folder/file%` to access `file.txt` in a subfolder called `folder`. I haven't tested this, but it may work... If not then I have to look at getting it to work somehow.

**Comment by kristophergeo** [comment]
ohh so u mean renaming the file to include its folder name?

**Comment by kristophergeo** [comment]
ohhh u mean make a new shortcut that redirects to the other shortcut?

**Comment by kristophergeo** [comment]
i tried this
![image](https://github.com/Andre601/Shortcut-Expansion/assets/114158743/c93e40fe-4b8a-460c-b58d-3077ec139ddc)
 but ye it didnt work 
![image](https://github.com/Andre601/Shortcut-Expansion/assets/114158743/d8008a90-4331-4d8a-8699-1b08c1c07fa2)

**Comment by kristophergeo** [comment]
if you do any testing yourself and find a solution @ me and let me know thankss 😙

**Comment by Andre601** [comment]
> i tried this
> ![image](https://github.com/Andre601/Shortcut-Expansion/assets/114158743/c93e40fe-4b8a-460c-b58d-3077ec139ddc)
>  but ye it didnt work 
> ![image](https://github.com/Andre601/Shortcut-Expansion/assets/114158743/d8008a90-4331-4d8a-8699-1b08c1c07fa2)
> 

I didn't mean like that.
I meant to use `%shortcut_folder/island_wheat_deposited%` where you currently use `%shortcut_island_wheat_deposited%`...

Obviously did it not work fo you since the expansion still looks for the file in the Shrtcuts folder.

**Comment by kristophergeo** [comment]
ohhh so replace the placeholder in the menu

**Comment by kristophergeo** [comment]
oooo u r giga smart! yee it works! thanks @Andre601 ❤️
